## FILE EXPORTATION STEPS
- **Step 1:**  Import the required Libraries.
- **Step 2:**  Get the Absolute path of the current working Directory (Which contains our raw files) and Change Directory 
- **Step 3:**  Get the absolute path of all our Csv files using **glob** library
- **Step 4:**   Loop through one file at a time and  read it into a data frame using **pandas**
- **Step 5:**   Change the data columns to the desired datatypes for Usuability
- **Step 6:**   Connect to the SQL data base and Push the raw file

###  Step 1: Import libraries

In [37]:
#Libraries
from sqlalchemy import create_engine
import pyodbc
import pandas as pd
import numpy as np
import glob
import os 
import urllib

In [ ]:
pip install pyodbc

- **sqlalchemy(create_engine):** - Acts as a translator; Provides connectivity between SQL and Python
    - Creates an engine that allows us send tables directly to our database without use of long SQL INSERT statements
- **pyodbc(PythonOpenDatabaseConnection):** - Bridge/driver that allows python to physically connect to SQLserver database, Low-level handshake between Computer and Database Server.
- **pandas:** - For reading csv files into dataframes(Structured tables)
- **numpy:**-  Handling Division by Zero in Population(#DIV/0!), mathematical computations. To handle NAN values. 
- **glob:** - File finder. that allows us to search for files using wild cards like *.csv insteading of typing them manually.
- **OS:** -  Allows python to talk to windows operating system. to tell our current working directory pathname
- **urllib:** - Converts illegal characters into format that the **create_engine** function can understand.

### Step II: Understand the Absolute path of our raw files

In [3]:
#Find out our current Working Directory
os.getcwd()

'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)'

In [38]:
#Change Directory to our current  Working Directory
os.chdir(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)')

In [39]:
#Fetch the Absolute paths for our individual raw files.
glob.glob(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data/Jamir Data*')

['D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2020.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2021.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2022.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2023.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2024.csv']

### Step III: Loop and Read the files into  dataframes

In [35]:
all_files = glob.glob('D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2020.csv')
dfs = []
for file in all_files:
    df1 = pd.read_csv(file)

In [36]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Columns: 487 entries, orgunitlevel1 to Population
dtypes: float64(199), int64(282), object(6)
memory usage: 612.7+ KB

In [26]:
df1.shape

(161, 487)

In [31]:
df1.head()

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,<5YRS MALE TOTAL,< 5YRS GRAND TOTAL,POPULATION IN 2014,POPULATION IN 2024,AREA(Km2),ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t],TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E)
0,Karamoja,Abim District,6,7,13,16161,9062,25223,16507,8054,...,15199,31801,107966.0,144084.0,2301.0,1.029278437,128376.1239,55.79144888,2.7067,33.6595
1,Acholi,Acholi,316,338,654,365422,214763,580185,456269,123147,...,185689,381335,1500762.0,2044355.0,28522.0,1.031393639,1806585.489,63.34007043,NaN,NaN
2,West Nile,Adjumani District,14,10,24,68996,51991,120987,60160,28387,...,43291,87673,107966.0,144084.0,2301.0,1.029278437,128376.1239,55.79144888,3.2549,31.7195
3,Acholi,Agago District,46,66,112,66256,39123,105379,58935,20260,...,32950,67991,227792.0,307235.0,3493.0,1.03037004,272582.3933,78.0367573,2.9251,33.3486
4,Lango,Alebtong District,3,5,8,7110,3851,10961,9974,3515,...,4274,8806,227541.0,283509.0,1534.0,1.022234935,259635.4412,169.253873,2.2914,33.2139

### Step IV:  Change columns to respective data types

In [ ]:
# Changing all necessary column values to Integer

In [32]:
import pandas as pd

for col in df1.columns:
    if pd.api.types.is_numeric_dtype(df1[col]):
        # If all non‑missing values are whole numbers, cast to Int64
        if (df1[col].dropna() % 1 == 0).all():
            df1[col] = df1[col].astype("Int64")   # nullable integer
        else:
            # Otherwise keep as float (decimals preserved)
            df1[col] = df1[col].astype("float")
    else:
        # Try to coerce text columns that look numeric, leave others untouched
        df1[col] = pd.to_numeric(df1[col], errors="ignore")

C:\Users\User\AppData\Local\Temp\ipykernel_6428\905795917.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df1[col] = pd.to_numeric(df1[col], errors="ignore")
C:\Users\User\AppData\Local\Temp\ipykernel_6428\905795917.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df1[col] = pd.to_numeric(df1[col], errors="ignore")
C:\Users\User\AppData\Local\Temp\ipykernel_6428\905795917.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df1[col] = pd.to_numeric(df1[col], errors="ignore")

In [ ]:
# Replace the specific error string with NaN, then convert
df1['Population'] = df1['Population'].replace('#DIV/0!', np.nan).astype(float)

In [24]:
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2021","105-EP01b. Malaria Total 0-28Dys, Female February 2021","105-EP01b. Malaria Total 0-28Dys, Female March 2021","105-EP01b. Malaria Total 0-28Dys, Female April 2021","105-EP01b. Malaria Total 0-28Dys, Female May 2021",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2021",Year,Population
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.321348e+05
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,40,22,40,23,14,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.863301e+06
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.321348e+05
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,2,1,0,4,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,2.808607e+05
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,<NA>,1,1,1,3,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,2.654084e+05

### Step V: Push the raw files to the SQL server Database

In [34]:
server = "DESKTOP-U507UFU\\MSSQLSERVER01"
database = "Malaria_DB"

conn_str = (
    "Driver={ODBC Driver 17 for SQL Server};"
    f"Server={server};"
    f"Database={database};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(conn_str)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

df1.to_sql(
    "Malaria2023",
    engine,
    if_exists="append",
    index=False
)

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1050.2'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

1

In [27]:
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2021","105-EP01b. Malaria Total 0-28Dys, Female February 2021","105-EP01b. Malaria Total 0-28Dys, Female March 2021","105-EP01b. Malaria Total 0-28Dys, Female April 2021","105-EP01b. Malaria Total 0-28Dys, Female May 2021",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2021","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2021",Year,Population
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.321348e+05
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,40,22,40,23,14,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.863301e+06
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,1.321348e+05
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,2,1,0,4,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,2.808607e+05
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,<NA>,1,1,1,3,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2021,2.654084e+05