## FILE EXPORTATION STEPS
- **Step 1:**  Import the required Libraries.
- **Step 2:**  Get the Absolute path of the current working Directory (Which contains our raw files) and Change Directory 
- **Step 3:**  Get the absolute path of all our Csv files using **glob** library
- **Step 4:**   Loop through one file at a time and  read it into a data frame using **pandas**
- **Step 5:**   Change the data columns to the desired datatypes for Usuability
- **Step 6:**   Connect to the SQL data base and Push the raw file

###  Step 1: Import libraries

In [18]:
#Libraries
from sqlalchemy import create_engine
import pyodbc
import pandas as pd
import numpy as np
import glob
import os 
import urllib

In [ ]:
pip install pyodbc

- **sqlalchemy(create_engine):** - Acts as a translator; Provides connectivity between SQL and Python
    - Creates an engine that allows us send tables directly to our database without use of long SQL INSERT statements
- **pyodbc(PythonOpenDatabaseConnection):** - Bridge/driver that allows python to physically connect to SQLserver database, Low-level handshake between Computer and Database Server.
- **pandas:** - For reading csv files into dataframes(Structured tables)
- **numpy:**-  Handling Division by Zero in Population(#DIV/0!), mathematical computations. To handle NAN values. 
- **glob:** - File finder. that allows us to search for files using wild cards like *.csv insteading of typing them manually.
- **OS:** -  Allows python to talk to windows operating system. to tell our current working directory pathname
- **urllib:** - Converts cryptic characters into format that the **create_engine** function can understand. Encoding Connection string

### Step II: Understand the Absolute path of our raw files

In [19]:
#Find out our current Working Directory
os.getcwd()

'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)'

In [20]:
#Change Directory to our current  Working Directory
os.chdir(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)')

In [21]:
#Fetch the Absolute paths for our individual raw files.
glob.glob(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data/Jamir Data*')

['D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2020.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2021.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2022.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2023.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2024.csv']

### Step III: Loop and Read the files into  dataframes (One at a time )

In [22]:
all_files = glob.glob('D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2020.csv')
dfs = []
for file in all_files:
    df1 = pd.read_csv(file)

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Columns: 487 entries, orgunitlevel1 to Population
dtypes: float64(199), int64(282), object(6)
memory usage: 612.7+ KB

In [24]:
df1.shape

(161, 487)

In [25]:
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2020","105-EP01b. Malaria Total 0-28Dys, Female February 2020","105-EP01b. Malaria Total 0-28Dys, Female March 2020","105-EP01b. Malaria Total 0-28Dys, Female April 2020","105-EP01b. Malaria Total 0-28Dys, Female May 2020",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2020",Year,Population
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,128376.1239
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,31.0,25.0,25.0,33.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,1806585.489
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,128376.1239
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,5.0,18.0,3.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,272582.3933
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,1.0,1.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,259635.4412

### Step IV:  Change columns to respective data types

In [26]:
#Change Numeric Column Values to Integer
for col in df1.columns:
    if pd.api.types.is_numeric_dtype(df1[col]):
        # If all non‑missing values are whole numbers, cast to Int64
        if (df1[col].dropna() % 1 == 0).all():
            df1[col] = df1[col].astype("Int64")   # nullable integer
        else:
            # Otherwise keep as float (decimals preserved)
            df1[col] = df1[col].astype("float")
    else:
        # Try to coerce text columns that look numeric, leave others untouched
        df1[col] = pd.to_numeric(df1[col], errors="ignore")

C:\Users\User\AppData\Local\Temp\ipykernel_13560\1702007171.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df1[col] = pd.to_numeric(df1[col], errors="ignore")
C:\Users\User\AppData\Local\Temp\ipykernel_13560\1702007171.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df1[col] = pd.to_numeric(df1[col], errors="ignore")

In [27]:
# Replace the specific error string with NaN, then convert
df1['Population'] = df1['Population'].replace('#DIV/0!', np.nan).astype(float)

In [ ]:
#Dataframe Inspection
df1.head()

### Step V: Push the raw files to the SQL server Database

In [ ]:
server = "DESKTOP-U507UFU\\MSSQLSERVER01"
database = "Malaria_DB"

conn_str = (
    "Driver={ODBC Driver 17 for SQL Server};"
    f"Server={server};"
    f"Database={database};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(conn_str)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

df1.to_sql(
    "Malaria2023",
    engine,
    if_exists="append",
    index=False
)

In [28]:
#Final Inspection
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2020","105-EP01b. Malaria Total 0-28Dys, Female February 2020","105-EP01b. Malaria Total 0-28Dys, Female March 2020","105-EP01b. Malaria Total 0-28Dys, Female April 2020","105-EP01b. Malaria Total 0-28Dys, Female May 2020",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2020","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2020",Year,Population
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,0,0,1,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020,1.283761e+05
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,31,25,25,33,26,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020,1.806585e+06
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,0,0,0,0,4,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020,1.283761e+05
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,5,18,3,1,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020,2.725824e+05
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,1,1,0,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020,2.596354e+05

In [ ]:
conn.close()