## FILE EXPORTATION STEPS
- **Step 1:**  Import the required Libraries.
- **Step 2:**  Get the Absolute path of the current working Directory (Which contains our raw files) and Change Directory 
- **Step 3:**  Get the absolute path of all our Csv files using **glob** library
- **Step 4:**   Loop through one file at a time and  read it into a data frame using **pandas**
- **Step 5:**   Change the data columns to the desired datatypes for Usuability
- **Step 6:**   Connect to the SQL data base and Push the raw file

###  Step 1: Import libraries

In [3]:
#Libraries
from sqlalchemy import create_engine
import pyodbc
import pandas as pd
import numpy as np
import glob
import os 
import urllib

In [2]:
pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

- **sqlalchemy(create_engine):** - Acts as a translator; Provides connectivity between SQL and Python
    - Creates an engine that allows us send tables directly to our database without use of long SQL INSERT statements
- **pyodbc(PythonOpenDatabaseConnection):** - Bridge/driver that allows python to physically connect to SQLserver database, Low-level handshake between Computer and Database Server.
- **pandas:** - For reading csv files into dataframes(Structured tables)
- **numpy:**-  Handling Division by Zero in Population(#DIV/0!), mathematical computations. To handle NAN values. 
- **glob:** - File finder. that allows us to search for files using wild cards like *.csv insteading of typing them manually.
- **OS:** -  Allows python to talk to windows operating system. to tell our current working directory pathname
- **urllib:** - Converts cryptic characters into format that the **create_engine** function can understand. Encoding Connection string

### Step II: Understand the Absolute path of our raw files

In [4]:
#Find out our current Working Directory
os.getcwd()

'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)'

In [5]:
#Change Directory to our current  Working Directory
os.chdir(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)')

In [6]:
#Fetch the Absolute paths for our individual raw files.
glob.glob(
'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data/Jamir Data*')

['D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2020.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2021.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2022.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2023.csv',
 'D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir Data 2024.csv']

### Step III: Loop and Read the files into  dataframes (One at a time )

In [47]:
all_files = glob.glob('D:\\Data Analyst\\MALARIA ANALYTICS\\FULL PROJECT\\Malaria data\\Raw data(Original Data)/Raw data\\Jamir data 2024.csv')
dfs = []
for file in all_files:
    df1 = pd.read_csv(file)

In [40]:
#DataType information
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Columns: 486 entries, orgunitlevel1 to 105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2023
dtypes: float64(187), int64(294), str(5)
memory usage: 611.4 KB

In [25]:
#Number of Rows and Columns
df1.shape

(161, 485)

In [48]:
#First 5 records of dataset
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2024","105-EP01b. Malaria Total 0-28Dys, Female February 2024","105-EP01b. Malaria Total 0-28Dys, Female March 2024","105-EP01b. Malaria Total 0-28Dys, Female April 2024","105-EP01b. Malaria Total 0-28Dys, Female May 2024",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male March 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male April 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2024"
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,2.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,37.0,20.0,35.0,20.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,3.0,3.0,0.0,2.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,1.0,1.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,1.0,1.0,2.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step IV:  Change columns to respective data types

In [49]:
#Change Numeric Column Values to Integer
for col in df1.columns:
    if pd.api.types.is_numeric_dtype(df1[col]):
        # If all non‑missing values are whole numbers, cast to Int64
        if (df1[col].dropna() % 1 == 0).all():
            df1[col] = df1[col].astype("Int64")   # nullable integer
        elif (df1[col].dropna() % 1 != 0).any():
            # Otherwise keep as float (decimals preserved)
             df1[col] = df1[col].astype("float")
        else:
            df1[col] = df1[col].astype("str")
    else:
        #Everything else (text, regions, etc)
        df1[col] = df1[col].astype("str")

In [50]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Columns: 485 entries, orgunitlevel1 to 105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2024
dtypes: Int64(480), str(5)
memory usage: 685.6 KB

In [51]:
#Dataframe Inspection
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2024","105-EP01b. Malaria Total 0-28Dys, Female February 2024","105-EP01b. Malaria Total 0-28Dys, Female March 2024","105-EP01b. Malaria Total 0-28Dys, Female April 2024","105-EP01b. Malaria Total 0-28Dys, Female May 2024",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male March 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male April 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2024"
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,2,0,1,<NA>,1,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,37,20,35,20,9,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,3,3,0,2,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,1,1,6,5,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,1,1,2,0,1,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Step V: Push the raw files to the SQL server Database

In [52]:
#Step 1: Define the Server instance and Database Name
server = "DESKTOP-U507UFU\\MSSQLSERVER01"
database = "MalariaLanding_DB"
#Step2: Instatiate a connection String 
conn_str = (
    "Driver={ODBC Driver 17 for SQL Server};"
    f"Server={server};"
    f"Database={database};"
    "Trusted_Connection=yes;"
)
#Step3: Connect to SQL database and Append raw files to the respective in form tables 
params = urllib.parse.quote_plus(conn_str)
engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}",
    fast_executemany=True 
                    
                      )

df1.to_sql(
    "Malaria2024",
    engine,
    if_exists="append",
    index=False,
    chunksize=10000
)

-1

### NOTE:
- Append: New data to the existing data.
- replace: Deletes/replaces the old data with New data
- Index=False; Deletes the index column from the dataframe before import to the DB.

In [53]:
#Final Inspection
df1.head()

,orgunitlevel1,orgunitlevel2,orgunitlevel3,organisationunitid,organisationunitname,"105-EP01b. Malaria Total 0-28Dys, Female January 2024","105-EP01b. Malaria Total 0-28Dys, Female February 2024","105-EP01b. Malaria Total 0-28Dys, Female March 2024","105-EP01b. Malaria Total 0-28Dys, Female April 2024","105-EP01b. Malaria Total 0-28Dys, Female May 2024",...,"105-MC04. Malaria in pregnancy 5-9Yrs, Male March 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male April 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male May 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male June 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male July 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male August 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male September 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male October 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male November 2024","105-MC04. Malaria in pregnancy 5-9Yrs, Male December 2024"
0,MOH - Uganda,Karamoja,Abim District,NREoMszwQZW,Abim District,2,0,1,<NA>,1,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,MOH - Uganda,Acholi,NaN,SUvODYOcaVf,Acholi,37,20,35,20,9,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,MOH - Uganda,West Nile,Adjumani District,QYiQ2KqgCxj,Adjumani District,3,3,0,2,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,MOH - Uganda,Acholi,Agago District,ztIyIYAzFKp,Agago District,1,1,6,5,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,MOH - Uganda,Lango,Alebtong District,p7EEgDEX3jT,Alebtong District,1,1,2,0,1,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>